version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-resume"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-u5qudbfk14nd"
s3_prefix = "aws-resume"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
